### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by boysim** [robimac04/busylight_mac#1]
Hi Robin,
Can you provide an installation guide?
Kind regards
Simon

**Comment by robimac04** [comment]
Hi Simon,

thanks for the reminder :-)
I'm working on it - I let you know.

Best regards,
Robin

**Comment by robimac04** [comment]
Please find the updated `README.md` with instructions on the main page.

**Comment by boysim** [comment]
thnx, everything works but... You should mention in the readme the locations for the changing the jabberstate. As mine are in dutch which leads to unrecognized statuses.

**Comment by robimac04** [comment]
You're right, thanks for letting me know.

I've added this to `README.md`...
